### ISSUE TITLE
"Error: postgres/print.alterTableAction: unsupported action "add_table_constraint_definition"" 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#15]
When running through the CLI flow with Postgres, I get this error after the step for `@updatedAt`:

```
✔ Done migrating @updatedAt? Press 'y' to continue … yes


Let's transition Prisma 1's 1-to-1 relations with @relation or @relation(link:INLINE) to unique constraints on the database. Run the following SQL command against your database:
      
Error: postgres/print.alterTableAction: unsupported action "add_table_constraint_definition"
    at alterTableAction (/Users/nikolasburk/Desktop/upgrade-guide/prisma-binding/dry-runs/prisma-binding-to-prisma2-base/node_modules/prisma-upgrade/dist/index.js:36:13)
    at Array.map (<anonymous>)
    at alterTableStmt (/Users/nikolasburk/Desktop/upgrade-guide/prisma-binding/dry-runs/prisma-binding-to-prisma2-base/node_modules/prisma-upgrade/dist/index.js:27:32)
    at stmt (/Users/nikolasburk/Desktop/upgrade-guide/prisma-binding/dry-runs/prisma-binding-to-prisma2-base/node_modules/prisma-upgrade/dist/index.js:18:14)
    at Array.map (<anonymous>)
    at print (/Users/nikolasburk/Desktop/upgrade-guide/prisma-binding/dry-runs/prisma-binding-to-prisma2-base/node_modules/prisma-upgrade/dist/index.js:12:16)
    at Object.upgrade (/Users/nikolasburk/Desktop/upgrade-guide/prisma-binding/dry-runs/prisma-binding-to-prisma2-base/node_modules/prisma-upgrade/dist/index.js:1206:30)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async main (/Users/nikolasburk/Desktop/upgrade-guide/prisma-binding/dry-runs/prisma-binding-to-prisma2-base/node_modules/prisma-upgrade/dist/cli/index.js:118:3)
```

This happens repeatedly when I re-run the CLI.

I'm using this Prisma 1 datamodel:

```graphql
type User {
  id: ID! @id
  email: String @unique
  name: String!
  posts: [Post!]!
  role: Role! @default(value: CUSTOMER)
  profile: Profile
  jsonData: Json 
}

type Post {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  title: String!
  content: String
  published: Boolean! @default(value: false)
  author: User @relation(link: TABLE)
  categories: [Category!]!
}

type Profile {
  id: ID! @id
  bio: String
  user: User! @relation(link: INLINE)
}

type Category {
  id: ID! @id
  name: String!
  posts: [Post!]!
}

enum Role {
  ADMIN
  CUSTOMER
}
```

**Comment by matthewmueller** [comment]
Please upgrade and try again :-)
