### ISSUE TITLE
CLI fails when connection URL is set via env var in Prisma 2 schema

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#5]
After running successfully through the SQL migration steps, I get the following error due to the connection URL set as an env var:

```
Let's transition Prisma 1's Json type to a json type in the database. Run the following SQL command against your database:
      
  ALTER TABLE User CHANGE jsonData jsonData json;

✔ Done migrating Json? Press 'y' to continue … yes

Error: datasource [object Object] "url" attribute must be a string, but got function_value
    at Datasource.get url [as url] (/Users/nikolasburk/Desktop/upgrade-guide/nexus-prisma/graphql/node_modules/prisma-upgrade/dist/index2.js:82:15)
    at reintrospect (/Users/nikolasburk/Desktop/upgrade-guide/nexus-prisma/graphql/node_modules/prisma-upgrade/dist/index.js:1465:19)
    at Object.upgrade (/Users/nikolasburk/Desktop/upgrade-guide/nexus-prisma/graphql/node_modules/prisma-upgrade/dist/index.js:1394:24)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async main (/Users/nikolasburk/Desktop/upgrade-guide/nexus-prisma/graphql/node_modules/prisma-upgrade/dist/cli/index.js:121:18)
```

**Comment by matthewmueller** [comment]
fixed in tmp-prisma-upgrade@0.0.12
